Repository CUK-CRUSH/Server, pull requests merged in 2024-01, with the labels that each got.

#18 Feat: 플레이리스트 이미지 기능 추가
  src/main/java/crush/myList/config/SwaggerConfig.java
  src/main/java/crush/myList/domain/music/Controller/MusicController.java
  src/main/java/crush/myList/domain/music/Dto/MusicDto.java
  src/main/java/crush/myList/domain/music/Entity/Music.java
  src/main/java/crush/myList/domain/music/Repository/MusicRepository.java
  src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
  src/main/java/crush/myList/domain/playlist/dto/PlaylistDto.java
  src/main/java/crush/myList/domain/playlist/entity/Playlist.java
  src/main/java/crush/myList/domain/playlist/repository/PlaylistRepository.java
  src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
Labels: enhancement

#36 UserDetails 설정 추가 및 테스트 코드 작성
  src/main/java/crush/myList/MyListApplication.java
  src/main/java/crush/myList/config/BeanConfig.java
  src/main/java/crush/myList/config/CorsConfig.java
  src/main/java/crush/myList/config/jwt/JwtTokenProvider.java
  src/main/java/crush/myList/config/security/SecurityMember.java
  src/main/java/crush/myList/config/security/SecurityMemberDto.java
  src/main/java/crush/myList/config/security/SecurityUserDetailsService.java
  src/main/java/crush/myList/domain/member/controller/MemberController.java
  src/main/java/crush/myList/domain/member/service/MemberService.java
  src/test/java/crush/myList/controller/MemberControllerTest.java
Labels: enhancement

#47 Fix: 배포 과정에서 도커 이미지 해시값 오류 해결
  .github/workflows/deploy-develop.yml
  .github/workflows/deploy-main.yml
Labels: bug

#58 Feat: 사용자, 플레이 리스트 더미 데이터 추가
  src/main/java/crush/myList/config/setup/DummyData.java
Labels: enhancement

#81 Feat: image 파일 webp 확장자로 변경 후 업로드
  build.gradle
  src/main/java/crush/myList/domain/image/service/ImageService.java
  src/main/resources/application.yml
  src/main/resources/img/test.jpg
  src/main/resources/img/test.png
  src/test/java/crush/myList/MyListApplicationTests.java
Labels: enhancement

#83 Feat: 사용자<->플레이리스트<->음악 양방향 관계 매핑
  src/main/java/crush/myList/domain/member/entity/Member.java
  src/main/java/crush/myList/domain/playlist/entity/Playlist.java
Labels: enhancement

#89 Feat: 음악 유튜브 url 정규식 검사
  src/main/java/crush/myList/config/jwt/JwtAuthenticationFilter.java
  src/main/java/crush/myList/config/jwt/JwtTokenProvider.java
  src/main/java/crush/myList/domain/music/Service/MusicService.java
  src/main/java/crush/myList/global/enums/LimitConstants.java
  src/test/java/crush/myList/controller/MusicControllerTest.java
  src/test/java/crush/myList/service/LoginServiceTest.java
  src/test/java/crush/myList/service/MemberServiceTest.java
Labels: enhancement

#96 Refactor: 더미 데이터 생성 수정
  src/main/java/crush/myList/config/setup/DummyData.java
  src/main/java/crush/myList/domain/playlist/repository/PlaylistRepository.java
Labels: bug

#97 Fix: 비속어 검사 메소드에서 BAD_REQUEST가 INTERNAL_SERVER_ERROR로 전송하던 버그 해결
  src/main/java/crush/myList/domain/member/service/UsernameService.java
Labels: bug

#98 리팩토링 및 API 변경
  .github/workflows/build.yml
  .github/workflows/deploy-develop.yml
  .github/workflows/deploy-main.yml
  src/main/java/crush/myList/config/EnvBean.java
  src/main/java/crush/myList/config/OAuth2/handler/LoginFailureHandler.java
  src/main/java/crush/myList/config/OAuth2/handler/LoginSuccessHandler.java
  src/main/java/crush/myList/config/jwt/JwtTokenProvider.java
  src/main/java/crush/myList/config/security/SecurityConfig.java
  src/main/java/crush/myList/config/setup/DummyData.java
  src/main/java/crush/myList/domain/image/service/ImageService.java
  src/main/java/crush/myList/domain/login/controller/LoginController.java
  src/main/java/crush/myList/domain/login/dto/ReissueReq.java
  src/main/java/crush/myList/domain/login/service/LoginService.java
  src/main/java/crush/myList/domain/member/controller/MemberController.java
  src/main/java/crush/myList/domain/member/dto/EditProfileReq.java
  src/main/java/crush/myList/domain/member/service/UsernameService.java
  src/main/resources/application-oauth2.yml
  src/test/java/crush/myList/MyListApplicationTests.java
  src/test/java/crush/myList/controller/MemberControllerTest.java
  src/test/java/crush/myList/service/ImageServiceTest.java
  src/test/java/crush/myList/service/LoginServiceTest.java
Labels: enhancement, refactoring
