Repository CUK-CRUSH/Server, pull requests merged in 2024-02, with the labels that each got.

#100 Feat: access token 유효시간 10분으로 변경
  src/main/java/crush/myList/domain/image/entity/Image.java
  src/main/java/crush/myList/domain/member/controller/MemberController.java
  src/main/java/crush/myList/domain/member/entity/Member.java
  src/main/java/crush/myList/domain/member/entity/Role.java
  src/main/java/crush/myList/domain/member/repository/MemberRepository.java
  src/main/java/crush/myList/domain/member/service/MemberService.java
  src/main/java/crush/myList/domain/music/Repository/MusicRepository.java
  src/main/java/crush/myList/domain/music/Service/MusicService.java
  src/main/java/crush/myList/domain/music/entity/Music.java
  src/main/java/crush/myList/domain/playlist/entity/Playlist.java
  src/main/java/crush/myList/global/entity/BaseEntity.java
  src/main/resources/application.yml
  src/test/java/crush/myList/controller/PlaylistControllerTest.java
  src/test/java/crush/myList/service/MemberServiceTest.java
  src/test/java/crush/myList/utils/TestEntityMaker.java
  src/test/java/crush/myList/utils/repository/MemberTestRepository.java
  src/test/java/crush/myList/utils/repository/RoleTestRepository.java
  src/test/java/crush/myList/utils/repository/TestRepository.java
Labels: enhancement

#99 Test: 테스트 코드 리팩터링
  src/main/java/crush/myList/domain/member/service/UsernameService.java
  src/test/java/crush/myList/controller/MusicControllerTest.java
  src/test/java/crush/myList/controller/PlaylistControllerTest.java
  src/test/java/crush/myList/controller/TestUtil.java
  src/test/java/crush/myList/service/UsernameServiceTest.java
Labels: refactoring

#104 Feat: GCS 이미지 경로 이슈 해결 및 토큰 발급시간 환경변수로 변경
  .github/workflows/build.yml
  .github/workflows/deploy-develop.yml
  .github/workflows/deploy-main.yml
  src/main/java/crush/myList/domain/image/service/ImageService.java
  src/main/resources/application.yml
Labels: bug

#115 Feat: 다중 음악 추가
  src/main/java/crush/myList/domain/music/Controller/MusicController.java
  src/main/java/crush/myList/domain/music/Service/MusicService.java
  src/test/java/crush/myList/controller/MusicControllerTest.java
  src/test/java/crush/myList/controller/PlaylistControllerTest.java
Labels: enhancement

#118 Fix: 음악 등록시 url 검사 로직 누락 수정
  src/main/java/crush/myList/domain/music/Service/MusicService.java
  src/test/java/crush/myList/service/GoogleAutocompleteTest.java
Labels: bug

#120 Feat: 플레이리스트 무작위 추천 기능 #112
  src/main/java/crush/myList/config/security/SecurityConfig.java
  src/main/java/crush/myList/domain/playlist/repository/PlaylistRepository.java
  src/main/java/crush/myList/domain/recommendation/controller/RecommendationController.java
  src/main/java/crush/myList/domain/recommendation/service/RandomRecommendationService.java
  src/main/java/crush/myList/domain/recommendation/service/Recommendation.java
  src/test/java/crush/myList/service/RandomRecommendationServiceTest.java
Labels: enhancement

#123 Recommendation Response에 유저네임 추가
  src/main/java/crush/myList/domain/recommendation/controller/RecommendationController.java
  src/main/java/crush/myList/domain/recommendation/dto/RecommendationDto.java
  src/main/java/crush/myList/domain/recommendation/service/RandomRecommendationService.java
  src/main/java/crush/myList/domain/recommendation/service/Recommendation.java
  src/test/java/crush/myList/service/RandomRecommendationServiceTest.java
Labels: enhancement

#124 Feat: playlist 좋아요 기능 추가
  src/main/java/crush/myList/config/security/SecurityConfig.java
  src/main/java/crush/myList/config/security/SecurityMember.java
  src/main/java/crush/myList/domain/music/Repository/MusicRepository.java
  src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
  src/main/java/crush/myList/domain/playlist/dto/PlaylistDto.java
  src/main/java/crush/myList/domain/playlist/entity/Playlist.java
  src/main/java/crush/myList/domain/playlist/entity/PlaylistLike.java
  src/main/java/crush/myList/domain/playlist/repository/PlaylistLikeRepository.java
  src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
  src/main/java/crush/myList/domain/recommendation/dto/RecommendationDto.java
  src/test/java/crush/myList/controller/PlaylistControllerTest.java
  src/test/java/crush/myList/controller/TestUtil.java
  src/test/java/crush/myList/service/RandomRecommendationServiceTest.java
Labels: enhancement

#128 Feat: 회원 탈퇴 기능 #125
  src/main/java/crush/myList/domain/member/controller/MemberController.java
  src/main/java/crush/myList/domain/member/service/MemberService.java
  src/test/java/crush/myList/controller/MemberControllerTest.java
  src/test/java/crush/myList/controller/TestUtil.java
Labels: enhancement

#133 플레이리스트 방명록 기능 및 오류 수정
  src/main/java/crush/myList/config/security/SecurityConfig.java
  src/main/java/crush/myList/domain/member/entity/Member.java
  src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
  src/main/java/crush/myList/domain/playlist/dto/GuestBookDto.java
  src/main/java/crush/myList/domain/playlist/dto/LikeMember.java
  src/main/java/crush/myList/domain/playlist/entity/GuestBook.java
  src/main/java/crush/myList/domain/playlist/entity/Playlist.java
  src/main/java/crush/myList/domain/playlist/repository/GuestBookRepository.java
  src/main/java/crush/myList/domain/playlist/service/GuestBookService.java
  src/main/java/crush/myList/domain/playlist/service/LikeService.java
  src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
  src/main/java/crush/myList/domain/search/service/SearchService.java
  src/test/java/crush/myList/controller/PlaylistControllerTest.java
  src/test/java/crush/myList/controller/TestUtil.java
Labels: enhancement

#134 Fix: 좋아요 누른 사용자 소개글 누락 수정
  src/main/java/crush/myList/domain/playlist/service/LikeService.java
Labels: bug

#135 refactor: search api 플레이리스트 결과 값 형식 수정
  src/main/java/crush/myList/config/setup/DummyData.java
  src/main/java/crush/myList/domain/search/dto/PlaylistDto.java
  src/main/java/crush/myList/domain/search/service/SearchService.java
  src/test/java/crush/myList/controller/SearchControllerTest.java
Labels: documentation, enhancement

#136 Feat unregistration
  src/main/java/crush/myList/domain/playlist/repository/PlaylistRepository.java
  src/main/java/crush/myList/domain/recommendation/service/RandomRecommendationService.java
  src/test/java/crush/myList/service/RandomRecommendationServiceTest.java
Labels: enhancement

#137 프론트 요구사항 반영
  src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
  src/main/java/crush/myList/domain/playlist/dto/GuestBookDto.java
  src/main/java/crush/myList/domain/playlist/service/GuestBookService.java
  src/main/java/crush/myList/domain/recommendation/dto/RecommendationDto.java
  src/main/java/crush/myList/domain/search/controller/SearchController.java
  src/main/java/crush/myList/domain/search/dto/PlaylistDto.java
  src/main/java/crush/myList/domain/search/dto/SearchDto.java
  src/main/java/crush/myList/domain/search/service/SearchService.java
  src/main/java/crush/myList/global/enums/LimitConstants.java
  src/test/java/crush/myList/controller/PlaylistControllerTest.java
  src/test/java/crush/myList/controller/TestUtil.java
Labels: enhancement, refactoring

#144 140 todo 플레이리스트 검색결과 수정
  src/main/java/crush/myList/domain/search/dto/PlaylistDto.java
  src/main/java/crush/myList/domain/search/service/SearchService.java
  src/test/java/crush/myList/controller/SearchControllerTest.java
Labels: enhancement

#145 141 todo 방명록 조회 api 응답 수정 #141
  src/main/java/crush/myList/domain/playlist/dto/GuestBookDto.java
  src/main/java/crush/myList/domain/playlist/service/GuestBookService.java
  src/test/java/crush/myList/controller/PlaylistControllerTest.java
Labels: enhancement

#148 방명록 / 플리 좋아요 조회 페이징
  src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
  src/main/java/crush/myList/domain/playlist/repository/GuestBookRepository.java
  src/main/java/crush/myList/domain/playlist/repository/PlaylistLikeRepository.java
  src/main/java/crush/myList/domain/playlist/service/GuestBookService.java
  src/main/java/crush/myList/domain/playlist/service/LikeService.java
  src/main/java/crush/myList/global/enums/LimitConstants.java
  src/test/java/crush/myList/controller/MemberControllerTest.java
  src/test/java/crush/myList/controller/PlaylistControllerTest.java
Labels: enhancement

#146 Feat: 검색 멤버 페이징 크기 5 -> 10
  src/main/java/crush/myList/global/enums/LimitConstants.java
Labels: enhancement

#150 MongoDB 적용 #122
  .github/workflows/build.yml
  .github/workflows/deploy-develop.yml
  .github/workflows/deploy-main.yml
  build.gradle
  src/main/java/crush/myList/config/BeanConfig.java
  src/main/java/crush/myList/config/EnvBean.java
  src/main/java/crush/myList/config/JpaConfig.java
  src/main/java/crush/myList/config/MongoConfig.java
  src/main/java/crush/myList/config/setup/DummyData.java
  src/main/java/crush/myList/config/setup/InitData.java
  src/main/java/crush/myList/domain/member/service/MemberService.java
  src/main/java/crush/myList/domain/music/Controller/MusicController.java
  src/main/java/crush/myList/domain/music/Dto/MusicDto.java
  src/main/java/crush/myList/domain/music/Repository/MusicJpaRepository.java
  src/main/java/crush/myList/domain/music/Service/MusicService.java
  src/main/java/crush/myList/domain/music/entity/MusicEntity.java
  src/main/java/crush/myList/domain/music/mongo/document/Music.java
  src/main/java/crush/myList/domain/music/mongo/repository/MusicRepository.java
  src/main/java/crush/myList/domain/playlist/entity/Playlist.java
  src/main/java/crush/myList/domain/playlist/service/LikeService.java
  src/main/java/crush/myList/domain/playlist/service/PlaylistService.java
  src/main/java/crush/myList/domain/recommendation/service/RandomRecommendationService.java
  src/main/java/crush/myList/domain/search/service/SearchService.java
  src/main/java/crush/myList/global/entity/BaseDocument.java
  src/main/java/crush/myList/global/enums/LimitConstants.java
  src/main/resources/application.yml
  src/test/java/crush/myList/controller/MemberControllerTest.java
  src/test/java/crush/myList/controller/MusicControllerTest.java
  src/test/java/crush/myList/controller/PlaylistControllerTest.java
  src/test/java/crush/myList/controller/SearchControllerTest.java
  src/test/java/crush/myList/controller/TestUtil.java
  src/test/java/crush/myList/service/RandomRecommendationServiceTest.java
  src/test/java/crush/myList/utils/TestEntityMaker.java
Labels: enhancement

#156 Fix: 좋아요 하면 회원탈퇴 불가능 버그 수정
  src/main/java/crush/myList/domain/member/controller/MemberController.java
  src/main/java/crush/myList/domain/member/entity/Member.java
  src/test/java/crush/myList/controller/MemberControllerTest.java
  src/test/java/crush/myList/controller/TestUtil.java
Labels: bug

#159 오류 수정 및 프론트 반영사항 적용
  src/main/java/crush/myList/config/setup/DummyData.java
  src/main/java/crush/myList/config/setup/InitData.java
  src/main/java/crush/myList/domain/music/Repository/MusicJpaRepository.java
  src/main/java/crush/myList/domain/music/Service/MusicService.java
  src/main/java/crush/myList/domain/music/entity/MusicEntity.java
  src/main/java/crush/myList/domain/search/service/SearchService.java
  src/test/java/crush/myList/controller/MusicControllerTest.java
Labels: bug, enhancement
