Repository CUK-CRUSH/Server, pull requests merged in 2024-04, with the labels that each got.

#207 Feat: 플레이리스트 수정 시 사용하는 음악 API 수정
  src/main/java/crush/myList/domain/login/controller/LoginController.java
  src/main/java/crush/myList/domain/music/Controller/MusicController.java
  src/main/java/crush/myList/domain/music/Dto/MusicDto.java
  src/main/java/crush/myList/domain/music/Service/MusicService.java
  src/main/java/crush/myList/domain/playlist/controller/PlaylistController.java
  src/main/java/crush/myList/domain/playlist/dto/PlaylistDto.java
  src/main/java/crush/myList/domain/playlist/entity/Playlist.java
  src/test/java/crush/myList/controller/MusicControllerTest.java
Labels: enhancement

#208 Feat: 음악 조회시 order 순서로 정렬
  src/main/java/crush/myList/domain/music/Controller/MusicController.java
  src/main/java/crush/myList/domain/music/Service/MusicService.java
  src/test/java/crush/myList/controller/MusicControllerTest.java
  src/test/java/crush/myList/controller/TestUtil.java
Labels: enhancement

#210 유튜브 비디오 검색 API 구현 #209
  .github/workflows/build.yml
  .github/workflows/deploy-develop.yml
  .github/workflows/deploy-main.yml
  build.gradle
  src/main/java/crush/myList/config/EnvBean.java
  src/main/java/crush/myList/domain/search/controller/SearchController.java
  src/main/java/crush/myList/domain/search/dto/ThumbnailDto.java
  src/main/java/crush/myList/domain/search/dto/VideoDto.java
  src/main/java/crush/myList/domain/search/service/SearchService.java
  src/main/java/crush/myList/global/enums/LimitConstants.java
  src/main/resources/application-youtube.yml
  src/main/resources/application.yml
  src/test/java/crush/myList/controller/SearchControllerTest.java
  src/test/java/crush/myList/controller/TestUtil.java
Labels: enhancement

#211 Fix: SSL 설정 원상복구 및 서버가 정상 작동하지 않는 이슈 해결
  src/main/resources/application.yml
Labels: bug

#213 Refactor: 유튜브 비디오 검색 API 리팩터링
  src/main/java/crush/myList/domain/search/controller/SearchController.java
  src/main/java/crush/myList/domain/search/service/SearchService.java
  src/main/java/crush/myList/exception/ErrorCode.java
  src/main/java/crush/myList/exception/GlobalExceptionHandler.java
Labels: refactoring
